[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18" # Puedes poner la versión de Node que usas en local

[[plugins]]
  package = "@netlify/plugin-nextjs"